language: cpp

dist: bionic

sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libgtest-dev # FIXME: make it work with cmake
    - cloc

before_install:
- export CC=gcc-7
- export CXX=g++-7

before_script:
- nproc
- which cmake

script:
- mkdir /tmp/gtest
- env -C /tmp/gtest cmake /usr/src/googletest -DCMAKE_CXX_FLAGS=-std=c++11 -Dgtest_disable_pthreads=1
- env -C /tmp/gtest sudo make install

- ./configure --examples --tests --benchmarks
- make
- make test
- cloc include
