language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libgtest-dev # FIXME: make it work with cmake
    - cloc

before_install:
- export CC=gcc-7
- export CXX=g++-7

script:
- ./configure --tests --benchmarks
- make
- make test
- cloc include
